apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-five-minute
spec:
  schedule: "0,5,10,15,20,25,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: priodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - image: luksa/batch-job
            name: kubia
  